name: rooute
description: "A lightweight, enum-centric routing framework for Flutter with platform-adaptive transitions and strongly-typed navigation."
version: 0.0.1
homepage: https://github.com/IbrahimKhatrii/rooute
repository: https://github.com/IbrahimKhatrii/rooute
issue_tracker: https://github.com/IbrahimKhatrii/rooute/issues
license: MIT
publish_to: "https://pub.dev"

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  platformer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
